use std::evm::effects::assert

pub struct Counter {
    pub value: u256,
}

fn inc() uses (counter: mut Counter) {
    counter.value = counter.value + 1
}

fn read() -> u256 uses (counter: Counter) {
    counter.value
}

fn bump_twice() -> u256 uses (counter: mut Counter) {
    inc()
    inc()
    read()
}

#[test]
fn test_bump_twice() {
    let mut counter = Counter { value: 0 }

    with (Counter = counter) {
        let value = bump_twice()
        assert(value == 2)
    }
}

